### ISSUE TITLE
Related Name clashes

### ISSUE THREAD

**Issue by novneetnov** [Radi85/Comment#40]
While trying to migrate the database after the installation, I am running into the following issue:

```
ERRORS:
comment.Flag.moderator: (fields.E304) Reverse accessor for 'Flag.moderator' clashes with reverse accessor for 'Flag.users'.
        HINT: Add or change a related_name argument to the definition for 'Flag.moderator' or 'Flag.users'.
waffle.Flag.users: (fields.E304) Reverse accessor for 'Flag.users' clashes with reverse accessor for 'Flag.moderator'.
        HINT: Add or change a related_name argument to the definition for 'Flag.users' or 'Flag.moderator'.
```

Looks like we have a clash of related_names. Is this a problem anyone else is facing? Let me know if you guys have solved it.
